version: '3'

services:
##########################
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mainDB
    ports:
      - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      - shared-network
##########################
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - ${PWD}/minio/data:/data
    networks:
      - shared-network
##########################
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/generators-test-bucket;
      /usr/bin/mc mb minio/generators-test-bucket;
      /usr/bin/mc policy set public minio/generators-test-bucket;
      tail -f /dev/null
      "      
    networks:
      - shared-network
##########################
  jupyter:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: jupyter-notebooks
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=mainDB
      - MINIO_ENDPOINT=minio
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "8889:8888"
    volumes:
      - ./jupyter-notebooks:/home/jovyan/work
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge

