services:
###############################################
  postgres:
    image: debezium/postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
###############################################
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" 
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

###############################################
  trino:
    image: trinodb/trino:latest
    ports:
      - "8080:8080" 
    volumes:
      - ./trino/catalog:/etc/trino/catalog 
      - ./trino/kafka:/etc/trino/kafka
    container_name: trino
    depends_on:
      - postgres
      - kafka
###############################################
  sqlpad:
    image: sqlpad/sqlpad:latest
    container_name: sqlpad
    ports:
      - "3000:3000"
    environment:
      # Admin user configuration
      - SQLPAD_ADMIN=admin@sqlpad.com
      - SQLPAD_ADMIN_PASSWORD=admin
      # Connection for the Postgres catalog
      - SQLPAD_CONNECTIONS__trino_postgres__name=trino_postgres
      - SQLPAD_CONNECTIONS__trino_postgres__driver=trino
      - SQLPAD_CONNECTIONS__trino_postgres__host=trino
      - SQLPAD_CONNECTIONS__trino_postgres__port=8080
      - SQLPAD_CONNECTIONS__trino_postgres__username=sqlpad
      - SQLPAD_CONNECTIONS__trino_postgres__catalog=postgres
      - SQLPAD_CONNECTIONS__trino_postgres__schema=nasdaq_order_book
      # Connection for the Kafka catalog
      - SQLPAD_CONNECTIONS__trino_kafka__name=trino_kafka
      - SQLPAD_CONNECTIONS__trino_kafka__driver=trino
      - SQLPAD_CONNECTIONS__trino_kafka__host=trino
      - SQLPAD_CONNECTIONS__trino_kafka__port=8080
      - SQLPAD_CONNECTIONS__trino_kafka__username=sqlpad
      - SQLPAD_CONNECTIONS__trino_kafka__catalog=kafka
      - SQLPAD_CONNECTIONS__trino_kafka__schema=default
    depends_on:
      - trino
###############################################
  eventgen:
    build:
      context: ./eventgen/
    container_name: eventgen
    command: sh -c 'sleep 10 && python /opt/eventgen/fake_event_generator.py'
    volumes:
      - ./eventgen:/opt/eventgen
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092


